### ISSUE TITLE
Upgrade to newest Socket.io.js version and verify that everything works

### ISSUE THREAD

**Issue by johannest** [johannest/webrtc#8]
Current version is 0.9.0
The newest one is 1.7.3

**Comment by Pasadena** [comment]
New version of Socket.io leads to CORS-issues with the used signalling server. Therefore I revert Socket.io back to 0.9.0. Perhaps the upgrade should be done after https://github.com/johannest/webrtc/issues/7 is resolved (and we can actually have control over the headers that server is using)

**Comment by gatanaso** [comment]
Version is updated to 2.0.1. Closing issue.
